version: '3'

services:

    phpfpm:
        build:
            context: ./php
            dockerfile: Dockerfile
        volumes:
            - ./app:/srv/www
            - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        networks:
             - www
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    nginx:
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - ./app:/srv/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - www
        depends_on:
            - phpfpm

    mysql:
        image: mysql:latest
        depends_on:
            - phpfpm
        networks:
            - www
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
    www: